### ISSUE TITLE
什么时候代码正式发布？

### ISSUE THREAD

**Issue by jiahong3837** [shinshoji01/Text-Hierarchical-ED#2]
什么时候代码正式发布？

**Comment by shinshoji01** [comment]
We've lost some implementation codes and been busy with other tasks. We are trying to restore the codes or re-implement them. So, it should be next month. I'm sorry for taking it so long.

**Comment by jiahong3837** [comment]
你好，我是邱家洪，邮件已经收到，谢谢。
